### ISSUE TITLE
Fix file copying issue in the publish to make pipeline repeatable

### ISSUE THREAD

**Issue by hklai** [istio-releases/pipeline#257]
Theoretically, one can re-trigger release pipeline by using the same set of parameters to rebuild the artifacts using the same SHA and version string.

This mostly works in the currently pipeline, where the "release-build" job can simply rebuild the artifacts.

However, there is a problem in https://github.com/istio/istio/blob/master/release/gcb/run_monthly_release.sh#L20 and https://github.com/istio/istio/blob/master/release/gcb/run_daily_release.sh#L20, which creates an extra level of nested folder in case the folder already exists (from the previous run).

This causes an failure subsequently when some files are not found in the expected location.

Example:
https://k8s-gubernator.appspot.com/build/istio-prow/logs/release-monthly/14?log#log

Suggestion:
run_monthly_release.sh and run_daily_release.sh can first check the existence of the target folder and remove it before copying.

**Comment by ibm-jason** [comment]
/cc @hklai, @linsun 

I'd like to assign this issue to myself. I just became a member of @istio and @istio-releases, but for some reason, I still cannot assign this issue to myself. Is there something that I'm missing here?

**Comment by ibm-jason** [comment]
@utka - As we discussed, in the interest of the pending release, I'll let you take over this task.
