### ISSUE TITLE
Automatically update  SHAs for daily releases.

### ISSUE THREAD

**Issue by utka** [istio-releases/pipeline#452]
We have 3 repos API, Proxy and Istio which are depending on one another.
When we create release, we have to submit 3 PRs in this order.
1. proxy change https://github.com/istio/proxy/pull/2120. Use latest SHA from API repo.
Merge the PR and use merged Proxy SHA for next PR.
2. istio change istio.deps(manually) and Gopkg.lock(run dep ensure command) https://github.com/istio/istio/pull/11857. Merge the PR.  And use SHA for next PR
3. And finally pipeline repo https://github.com/istio-releases/pipeline/pull/333

It would be nice if we submit PRs for #1 and #2 automatically nightly.
Even if we have #1 and #2 in 2 consecutive days it will work as well.

**Comment by icygalz** [comment]
This is not needed anymore since istio/istio move to use go.mod. Closing this issue.
